dataset:
  fixed_image_shape:
  - 1080
  - 1080
  - 1

  moving_image_shape:
  - 1080
  - 1080
  - 1

  moving_label_shape:
  - 30
  - 3
  fixed_label_shape:
  - 30
  - 3
  test:
    dir:
    - "/home/brian/data4/brian/PBnJ/jelly_processed_data/h5"
    format: "h5"
    labeled: false
  train:
    dir:
      - "/home/brian/data4/brian/PBnJ/jelly_processed_data/h5"
    format: "h5"
    labeled: true
  type: paired
  valid:
    dir:
      - "/home/brian/data4/brian/PBnJ/jelly_processed_data/h5"
    format: "h5"
    labeled: true
    sample_label: "all"
train:
  backbone:
    extract_levels:
    - 0
    - 1
    - 2
    - 3
    name: "local"
    num_channel_initial: 16
  epochs: 10
  loss:
    image: # TODO: Mask loss to part we care about
      kernel_size: 16
      name: "lncc"
      weight: 100
    label:
      name: "centroid"
      weight: 0.1
    # regularization:
    #   hybrid: true
    #   img_size:
    #   - 1080
    #   - 1080
    #   - 1
    #   name: "hybrid"
    #   weight: 1
    #   hybrid_weight:
    #     "axisdiff": 0.001
    #     "gradient": 0.02
    #     "nonrigid": 0.02
    #     "diff": 0.005
  method: "ddf"
  optimizer:
    learning_rate: 0.0001
    name: "Adam"
  preprocess:
    batch_size: 8
    data_augmentation:
      name: "centroid_affine"
      moving_label_size:
        - 30
        - 3
      fixed_label_size:
        - 30
        - 3
    num_parallel_calls: -1
    shuffle_buffer_num_batch: 4
  save_period: 1
  single_channel: True
