name: JFBAN
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - bzip2=1.0.8
  - ca-certificates=2025.1.31
  - ld_impl_linux-64=2.43
  - libexpat=2.6.4
  - libffi=3.4.6
  - libgcc=14.2.0
  - libgcc-ng=14.2.0
  - libgomp=14.2.0
  - liblzma=5.6.4
  - liblzma-devel=5.6.4
  - libnsl=2.0.1
  - libsqlite=3.49.1
  - libuuid=2.38.1
  - libxcrypt=4.4.36
  - libzlib=1.3.1
  - ncurses=6.5
  - openssl=3.5.0
  - pip=25.0.1
  - pygments=2.19.1
  - python=3.11.9
  - python-devtools=0.12.2
  - readline=8.2
  - setuptools=75.8.0
  - six=1.17.0
  - tk=8.6.13
  - wheel=0.45.1
  - xz=5.6.4
  - xz-gpl-tools=5.6.4
  - xz-tools=5.6.4
  - pip:
      - absl-py==2.1.0
      - alabaster==1.0.0
      - anyio==4.8.0
      - argon2-cffi==23.1.0
      - argon2-cffi-bindings==21.2.0
      - argparse==1.4.0
      - arrow==1.3.0
      - aspy-refactor-imports==3.0.2
      - astroid==3.3.8
      - asttokens==3.0.0
      - astunparse==1.6.3
      - async-lru==2.0.4
      - attrs==25.1.0
      - babel==2.17.0
      - beautifulsoup4==4.13.3
      - black==25.1.0
      - bleach==6.2.0
      - cachetools==5.5.2
      - certifi==2025.1.31
      - cffi==1.17.1
      - cfgv==3.4.0
      - chardet==5.2.0
      - charset-normalizer==3.4.1
      - click==8.1.8
      - colorama==0.4.6
      - comm==0.2.2
      - contourpy==1.3.1
      - coverage==7.6.12
      - cycler==0.12.1
      - debugpy==1.8.12
      - decorator==5.2.1
      - defusedxml==0.7.1
      - dill==0.3.9
      - distlib==0.3.9
      - docker==7.1.0
      - docutils==0.21.2
      - entrypoints==0.4
      - etils==1.12.0
      - executing==2.2.0
      - fastjsonschema==2.21.1
      - filelock==3.17.0
      - flake8==7.1.2
      - flatbuffers==25.2.10
      - fonttools==4.56.0
      - fqdn==1.5.1
      - fsspec==2025.2.0
      - gast==0.6.0
      - gitdb==4.0.12
      - gitpython==3.1.44
      - google-auth==2.38.0
      - google-auth-oauthlib==1.2.1
      - google-pasta==0.2.0
      - grpcio==1.70.0
      - gviz-api==1.10.0
      - h11==0.14.0
      - h5py==3.13.0
      - httpcore==1.0.7
      - httpx==0.28.1
      - hungarian-algorithm==0.1.11
      - identify==2.6.8
      - idna==3.10
      - imageio==2.37.0
      - imagej==0.3.2
      - imagesize==1.4.1
      - imglyb==2.1.0
      - importlib-resources==6.5.2
      - iniconfig==2.0.0
      - ipykernel==6.29.5
      - ipympl==0.9.7
      - ipython==8.32.0
      - ipywidgets==8.1.5
      - isoduration==20.11.0
      - isort==6.0.0
      - jedi==0.19.2
      - jgo==1.0.6
      - jinja2==3.1.5
      - joblib==1.4.2
      - jpype1==1.5.2
      - json5==0.10.0
      - jsonpointer==3.0.0
      - jsonschema==4.23.0
      - jsonschema-specifications==2024.10.1
      - jupyter-client==8.6.3
      - jupyter-core==5.7.2
      - jupyter-events==0.12.0
      - jupyter-lsp==2.2.5
      - jupyter-server==2.15.0
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.3.5
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.27.3
      - jupyterlab-widgets==3.0.13
      - keras==2.15.0
      - kiwisolver==1.4.8
      - labeling==0.1.14
      - lazy-loader==0.4
      - libclang==18.1.1
      - lxml==5.3.1
      - m2r2==0.3.3.post2
      - markdown==3.7
      - markdown-it-py==3.0.0
      - markupsafe==3.0.2
      - matplotlib==3.10.0
      - matplotlib-inline==0.1.7
      - mccabe==0.7.0
      - mdurl==0.1.2
      - mistune==0.8.4
      - ml-dtypes==0.2.0
      - mpmath==1.3.0
      - mypy-extensions==1.0.0
      - namex==0.0.8
      - nbclient==0.10.2
      - nbconvert==6.5.4
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - networkx==3.4.2
      - nibabel==5.3.2
      - nodeenv==1.9.1
      - notebook==7.3.2
      - notebook-shim==0.2.4
      - numpy==1.26.4
      - nvidia-cublas-cu12==12.4.5.8
      - nvidia-cuda-cupti-cu12==12.4.127
      - nvidia-cuda-nvrtc-cu12==12.4.127
      - nvidia-cuda-runtime-cu12==12.4.127
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.2.1.3
      - nvidia-curand-cu12==10.3.5.147
      - nvidia-cusolver-cu12==11.6.1.9
      - nvidia-cusparse-cu12==12.3.1.170
      - nvidia-cusparselt-cu12==0.6.2
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvtx-cu12==12.4.127
      - oauthlib==3.2.2
      - opencv-python==4.11.0.86
      - opt-einsum==3.4.0
      - optree==0.14.0
      - overrides==7.7.0
      - packaging==24.2
      - pandas==2.2.3
      - pandocfilters==1.5.1
      - parso==0.8.4
      - pathspec==0.12.1
      - pexpect==4.9.0
      - pillow==11.1.0
      - platformdirs==4.3.6
      - pluggy==1.5.0
      - pre-commit==4.1.0
      - prometheus-client==0.21.1
      - prompt-toolkit==3.0.50
      - protobuf==4.25.6
      - psutil==7.0.0
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.1
      - pycodestyle==2.12.1
      - pycparser==2.22
      - pydocstyle==6.3.0
      - pydot==3.0.4
      - pyflakes==3.2.0
      - pyimagej==1.6.0
      - pylint==3.3.4
      - pyparsing==3.2.1
      - pyproject-api==1.9.0
      - pystackreg==0.2.8
      - pytest==8.3.4
      - pytest-cov==6.0.0
      - pytest-dependency==0.6.0
      - python-dateutil==2.9.0.post0
      - python-json-logger==3.2.1
      - pytz==2025.1
      - pyyaml==6.0.2
      - pyzmq==26.2.1
      - referencing==0.36.2
      - requests==2.32.3
      - requests-oauthlib==2.0.0
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rich==13.9.4
      - roman-numerals-py==3.1.0
      - rpds-py==0.23.1
      - rsa==4.9
      - scikit-image==0.25.2
      - scikit-learn==1.6.1
      - scipy==1.15.2
      - scyjava==1.10.2
      - seed-isort-config==2.2.0
      - send2trash==1.8.3
      - smmap==5.0.2
      - sniffio==1.3.1
      - snowballstemmer==2.2.0
      - soupsieve==2.6
      - sphinx==8.2.1
      - sphinx-notfound-page==1.1.0
      - sphinx-rtd-theme==3.0.2
      - sphinx-tabs==3.4.7
      - sphinxcontrib-applehelp==2.0.0
      - sphinxcontrib-devhelp==2.0.0
      - sphinxcontrib-htmlhelp==2.1.0
      - sphinxcontrib-jquery==4.1
      - sphinxcontrib-jsmath==1.0.1
      - sphinxcontrib-qthelp==2.0.0
      - sphinxcontrib-serializinghtml==2.0.0
      - stack-data==0.6.3
      - sympy==1.13.1
      - tabulate==0.9.0
      - tensorboard==2.15.2
      - tensorboard-data-server==0.7.2
      - tensorboard-plugin-profile==2.19.0
      - tensorflow==2.15.0
      - tensorflow-estimator==2.15.0
      - tensorflow-io-gcs-filesystem==0.37.1
      - termcolor==2.5.0
      - terminado==0.18.1
      - testfixtures==8.3.0
      - threadpoolctl==3.6.0
      - tifffile==2025.2.18
      - tinycss2==1.4.0
      - tomlkit==0.13.2
      - torch==2.6.0
      - tornado==6.4.2
      - tox==4.24.1
      - tqdm==4.67.1
      - traitlets==5.14.3
      - triton==3.2.0
      - types-python-dateutil==2.9.0.20241206
      - typing-extensions==4.12.2
      - tzdata==2025.1
      - uri-template==1.3.0
      - urllib3==2.3.0
      - virtualenv==20.29.2
      - wcwidth==0.2.13
      - webcolors==24.11.1
      - webencodings==0.5.1
      - websocket-client==1.8.0
      - werkzeug==3.1.3
      - widgetsnbextension==4.0.13
      - wrapt==1.14.1
      - xarray==2025.1.2
      - zipp==3.21.0