dataset:
  fixed_image_shape:
  - 1080
  - 1080
  - 2
  fixed_label_shape:
  - 30
  - 3
  moving_image_shape:
  - 1080
  - 1080
  - 2
  moving_label_shape:
  - 30
  - 3
  test:
    dir:
    - /home/brian/data4/brian/PBnJ/test_data/stripes_padded
    format: h5
    labeled: false
  train:
    dir:
    - /home/brian/data4/brian/PBnJ/test_data/stripes_padded
    format: h5
    labeled: true
  type: paired
  valid:
    dir:
    - /home/brian/data4/brian/PBnJ/test_data/stripes_padded
    format: h5
    labeled: true
    sample_label: all
train:
  backbone:
    extract_levels:
    - 0
    - 1
    - 2
    - 3
    name: local
    num_channel_initial: 16
  epochs: 300
  loss:
    image:
      kernel_size: 16
      name: lncc
      weight: 100
    label:
      name: centroid
      weight: 0.1
  method: ddf
  optimizer:
    learning_rate: 0.0001
    name: Adam
  preprocess:
    batch_size: 8
    data_augmentation: null
    shuffle_buffer_num_batch: 4
  save_period: 1
  single_channel: true
