dataset:
  fixed_image_shape:
  - 1080
  - 1080
  - 1
  fixed_label_shape:
  - 30
  - 3
  moving_image_shape:
  - 1080
  - 1080
  - 1
  moving_label_shape:
  - 30
  - 3
  test:
    dir:
    - /home/brian/data4/brian/PBnJ/jelly_processed_data/mixed_lab_h5/val
    format: h5
    labeled: false
  train:
    dir:
    - /home/brian/data4/brian/PBnJ/jelly_processed_data/mixed_lab_h5/train
    format: h5
    labeled: true
  type: paired
  valid:
    dir:
    - /home/brian/data4/brian/PBnJ/jelly_processed_data/mixed_lab_h5/val
    format: h5
    labeled: true
    sample_label: all
train:
  backbone:
    extract_levels:
    - 0
    - 1
    - 2
    - 3
    name: local
    num_channel_initial: 16
  epochs: 300
  loss:
    image:
      kernel_size: 16
      name: lncc
      weight: 10000
    label:
      name: centroid
      weight: 10
  method: ddf
  optimizer:
    learning_rate: 0.0001
    name: Adam
  preprocess:
    batch_size: 8
    data_augmentation:
      fixed_label_size:
      - 30
      - 3
      moving_label_size:
      - 30
      - 3
      name: centroid_affine
    num_parallel_calls: -1
    shuffle_buffer_num_batch: 4
  save_period: 1
  single_channel: true
