## This is the configuration file that worked for me in creating the 
## multi-animal RFamide network. It was given 100 frames from each animal.
## It seems to have plateaued at about 350 epochs, but given than the non-RFa
## animals might be a harder problem, you might want to try running it for longer.

dataset:
  fixed_image_shape:
  - 1024
  - 1024
  - 3
  fixed_label_shape:
  - 30
  - 3
  moving_image_shape:
  - 1024
  - 1024
  - 3
  moving_label_shape:
  - 30
  - 3
  test:
    dir:
    - /home/brian/data4/brian/PBnJ/jelly_h5s/RFamide/unlab_big/d_pad/cropped/val
    format: h5
    labeled: false
  train:
    dir:
    - /home/brian/data4/brian/PBnJ/jelly_h5s/RFamide/unlab_big/d_pad/cropped/train
    format: h5
    labeled: true
  type: paired
  valid:
    dir:
    - /home/brian/data4/brian/PBnJ/jelly_h5s/RFamide/unlab_big/d_pad/cropped/val
    format: h5
    labeled: true
    sample_label: all
train:
  backbone:
    extract_levels:
    - 0
    - 1
    - 2
    - 3
    name: local
    num_channel_initial: 16
  epochs: 1000
  loss:
    image:
      kernel_size: 64
      name: lncc
      weight: 1000
    label:
      name: centroid
      weight: 0.001
    regularization:
      hybrid: true
      hybrid_weight:
        axisdiff: 0.001
        diff: 0.001
        gradient: 0.002
        nonrigid: 0.001
      img_size:
      - 1024
      - 1024
      - 3
      name: hybrid
      weight: 1
  method: ddf
  optimizer:
    learning_rate: 0.002
    name: Adam
  preprocess:
    batch_size: 4
    data_augmentation:
      batch_size: 4
      fixed_image_size:
      - 1024
      - 1024
      - 3
      moving_image_size:
      - 1024
      - 1024
      - 3
      name: affine
      scale: 0.005
    shuffle_buffer_num_batch: 4
  save_period: 1
  single_channel: true
